---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: urlaubsverwaltung-mariadb
  labels:
    app: urlaubsverwaltung-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
