apiVersion: v1
name: urlaubsverwaltung
version: 0.1.0
appVersion: 3.0.0
description: Die Urlaubsverwaltung ist eine Web-Anwendung, die es ermöglicht, Urlaubsanträge von Mitarbeitern elektronisch zu verwalten.
keywords:
  - urlaub
home: https://github.com/synyx/urlaubsverwaltung
sources:
  - https://github.com/synyx/urlaubsverwaltung
maintainers:
  - name: Johannes Graf
    email: graf@synyx.de
  - name: Tobias Schneider
    email: schneider@synyx.de
