image:
  tag: 3.0.0

applicationProperties: |-
  # AUTHENTICATION
  uv.security.auth=default
  uv.development.testdata.create=true

# use mariadb to store data
deployMariaDb: true

# mariadb related config options
mariadb:
  db:
    user: urlaubsverwaltung
    password: secret
    name: urlaubsverwaltung
  replication:
    enabled: false
  master:
    persistence:
      size: 512Mi
