{{- if .Values.secrets.ldapManagerDn }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "urlaubsverwaltung.fullname" . }}-ldap-manager
  labels:
    app.kubernetes.io/name: {{ include "urlaubsverwaltung.name" . }}
    helm.sh/chart: {{ include "urlaubsverwaltung.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ldapManagerDn: {{ .Values.secrets.ldapManagerDn | b64enc }}
  ldapManagerPassword: {{ .Values.secrets.ldapManagerPassword | b64enc }}
{{end}}
{{- if .Values.secrets.ldapSyncUserDn }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "urlaubsverwaltung.fullname" . }}-ldap-sync
  labels:
    app.kubernetes.io/name: {{ include "urlaubsverwaltung.name" . }}
    helm.sh/chart: {{ include "urlaubsverwaltung.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ldapSyncUserDn: {{ .Values.secrets.ldapSyncUserDn | b64enc }}
  ldapSyncPassword: {{ .Values.secrets.ldapSyncPassword | b64enc }}
{{end}}
{{- if not .Values.deployMariaDb }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "urlaubsverwaltung.fullname" . }}-mariadb
  labels:
    app.kubernetes.io/name: {{ include "urlaubsverwaltung.name" . }}
    helm.sh/chart: {{ include "urlaubsverwaltung.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  databaseUser: {{ .Values.secrets.databaseUser | b64enc }}
  databasePassword: {{ .Values.secrets.databasePassword | b64enc }}
{{end}}
