version: '2.4'
services:
  mariadb:
    image: mariadb:10.4
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    env_file:
      - db.env
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "bash", "-c", "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""]
      interval: 3s
      timeout: 1s
      retries: 5
  app:
    image: synyx/urlaubsverwaltung:latest
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: 'default'
    env_file:
      - db.env
    volumes:
      - ./application.properties:/app/application.properties
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 5

volumes:
  mariadb_data: {}
